// Freezer 14 (-20) antibody inventory, 2026 count — the lab's own sheet.
// Applied as a CORRECTION pass over the antibodies already in the app: the
// v5 import took these rows but lost the aliquot counts, several box IDs and
// some of the antibody detail. Nothing here deletes an existing record.
//
// [0 catalog, 1 name, 2 vendor, 3 animal, 4 clonality, 5 clone, 6 isotype,
//  7 reactivity, 8 uses, 9 box, 10 storage, 11 vials, 12 aliquots, 13 date, 14 notes]
export const SEED_F14 = [
  ["ab1101", "P53", "Abcam", "Mouse", "M", "DO-1", "IgG2a", "Human", "WB, ICC/IF, ChIP, Flow Cyt (Intra), IHC-P", "P53 Bpx", "Frezer 14 (-20)", 0, 21, "2015", ""],
  ["ab33889", "p-P53 (S392)", "Abcam", "Rabbit", "M", "EP155Y", "IgG", "Mouse, Rat, Human", "WB, IHC-P, IP, Dot", "P53 Bpx", "Frezer 14 (-20)", 0, 17, "2015", ""],
  ["ab1431", "p-P53 (S15)", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB", "P53 Bpx", "Frezer 14 (-20)", 0, 10, "", "Discontinued"],
  ["610420", "Caveolin", "BD Biosciences", "Mouse", "M", "C-26", "IgG1", "Rat, Mouse, Rabbit", "WB, IHC", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab9485", "GAPDH", "Abcam", "Rabbit", "P", "", "IgG", "Human, Mouse", "WB, IHC-P, ICC/IF", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["SOD-101", "Cu/Zn SOD", "Stress Gen", "Rabbit", "", "", "", "Human, Mouse, Rat", "WB, IHC", "GAPDH", "Frezer 14 (-20)", 1, 3, "", ""],
  ["ADI-SOD-101", "Cu/Zn SOD", "ENZO", "Rabbit", "", "", "", "Human, Mouse, Rat", "WB", "GAPDH", "Frezer 14 (-20)", 1, 0, "2015", ""],
  ["ab15148", "E-Cadherin", "Abcam", "Rabbit", "P", "", "IgG", "Human", "IHC-P", "GAPDH", "Frezer 14 (-20)", 1, 3, "", ""],
  ["ab197020", "Neuradminase", "Abcam", "Rabbit", "M", "EPR15712", "IgG", "Human", "WB", "GAPDH", "Frezer 14 (-20)", 0, 7, "", ""],
  ["ab209930", "IL-10 -PE", "Abcam", "Rabbit", "M", "EPR1114", "IgG", "Human", "Flow Cyto, ICC", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["STN-271383", "HSP70", "Abcam", "", "", "", "", "", "", "GAPDH", "Frezer 14 (-20)", 2, 0, "", ""],
  ["STN-271256", "CD81", "Abcam", "", "", "", "", "", "", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["STN-271330", "CD63", "Abcam", "", "", "", "", "", "", "GAPDH", "Frezer 14 (-20)", 2, 0, "", ""],
  ["AB129450", "PGP", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, IP", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["13342S", "MDR1/ABCD1", "Cell Signaling", "Rabbit", "M", "E1Y7B", "IgG", "Human", "WB, IP,IF", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab170904", "PGP", "Abcam", "Rabbit", "M", "EPR10364-57", "IgG", "Mouse, Rat, Human", "WB, IHC-P", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab3452", "NHERF1", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Human, Dog, Rat", "IHC-P, IP, WB, ICC, IHC-Fr", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab229193", "BCRP", "Abcam", "Rabbit", "M", "EPR21122", "IgG", "Human", "IHC-P, ICC/IF, Flow Cyt", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["NBP168254", "CD9", "Novus Biologics", "Rabbit", "", "", "", "", "", "GAPDH", "Frezer 14 (-20)", 1, 0, "", "Discountinued"],
  ["PA1823A", "PPARy", "Invitrogen", "Rabbit", "P", "", "IgG", "Human, Mouse, Rat", "WB, IHC, IF, IP,ChIP", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["14976082", "Alpha Smooth Muscle Actin", "Invitrogen", "Mouse", "M", "1A4", "IgG2a", "Human, Mouse, Rat", "WB, IHC,IF, FLOW, IP", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB109361", "ICAM1", "Abcam", "Rabbit", "M", "EPR4776", "IgG", "Human", "ICC/IF, IHC-P, IP, WB, Flow Cyt (Intra)", "GAPDH", "Frezer 14 (-20)", 1, 0, "", ""],
  ["NB10065805", "CD81", "Novus Biologics", "Mouse", "M", "1D6", "", "Human, Mouse, Goat, Monkey, Sheep", "WB, Simple Western, DB, ELISA, Flow, ICC/IF, IHC, IP, CyTOF-ready", "GAPDH", "Frezer 14 (-20)", 0, 11, "2022", ""],
  ["NBP200441", "LY6G", "Novus Biologics", "Rat", "M", "RB6-8C5", "", "Human Mouse", "WB, Flow, Func, ICC/IF, IHC, IP, CyTOF-ready", "GAPDH", "Frezer 14 (-20)", 0, 3, "2020", ""],
  ["AB52237", "Cox2", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, ICC/IF", "Antibody Box 1", "Frezer 14 (-20)", 0, 1, "", ""],
  ["AB28856", "p-NFKB P65", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, IHC-P", "Antibody Box 1", "Frezer 14 (-20)", 0, 12, "2019", "Labeled REL-A"],
  ["ab11370", "Connexin", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Rat, Cow, Dog, Human, Monkey, Pig, Hamster", "WB, IHC-Fr, IHC-P, ICC", "Antibody Box 1", "Frezer 14 (-20)", 0, 6, "", "Labeled CD43"],
  ["TA150052", "EGFP", "Origene", "Mouse", "M", "5A2", "IgG1", "Human", "WB", "Antibody Box 1", "Frezer 14 (-20)", 0, 12, "", "A full length eGFP tagged recombinant protein expressed in HEK293T cell"],
  ["AB86299", "p-NFKB (S536)", "Abcam", "Rabbit", "P", "", "IgG", "Human", "IHC-P, WB", "Antibody Box 1", "Frezer 14 (-20)", 0, 10, "", ""],
  ["ab137967", "E.coli", "Abcam", "Rabbit", "P", "", "IgG", "E.coli", "ELISA, ICC/IF", "E.coli Box", "Frezer 14 (-20)", 0, 17, "", ""],
  ["ab1793", "TNF-a", "Abcam", "Mouse", "M", "52B83", "IgG1", "Mouse, Rhesus monkey, Guinea pig, Human", "Flow Cyt (Intra), WB, ELISA, ICC/IF", "E.coli Box", "Frezer 14 (-20)", 0, 21, "", ""],
  ["", "PIGF", "", "", "", "", "", "", "", "E.coli Box", "Frezer 14 (-20)", 0, 12, "", ""],
  ["ab42789", "Nitro Tyrosine", "Abcam", "Rabbit", "P", "", "IgG", "This antibody reacts with free and bound nitrotyrosine.", "WB, IHC-FoFr, ELISA, IHC-P", "Antibody Box 1", "Frezer 14 (-20)", 0, 8, "", ""],
  ["AB133303", "NADPH", "Abcam", "Rabbit", "M", "UOTR1B493", "IgG", "Human Rat", "WB, IHC, IF, Flow", "E.coli Box", "Frezer 14 (-20)", 0, 8, "", "Discountinued"],
  ["NBP183347", "NOX1", "Novus Biologics", "Rabbit", "", "", "", "", "", "Nox Box", "Frezer 14 (-20)", 0, 3, "", "Discountinued"],
  ["NBP141012", "NOX2", "Novus Biologics", "Mouse", "M", "NL7", "IgG", "Human", "WB, ELISA, Flow, IHC", "Nox Box", "Frezer 14 (-20)", 0, 3, "", ""],
  ["NBP170856", "NOX3", "Novus Biologics", "Rabbit", "", "", "", "", "", "Nox Box", "Frezer 14 (-20)", 0, 2, "", "Discountinued"],
  ["NBP180899", "NOX5", "Novus Biologics", "Rabbit", "", "", "", "", "", "Nox Box", "Frezer 14 (-20)", 0, 5, "", "Discountinued"],
  ["AB31238", "LOX", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Human", "WB", "Nox Box", "Frezer 14 (-20)", 0, 5, "", ""],
  ["AB85839", "LOX1", "Abcam", "Rabbit", "P", "", "IgG", "Human", "IHC-R, WB, IHC-P", "Nox Box", "Frezer 14 (-20)", 0, 4, "", "Discontinued"],
  ["AB122263", "LOXL3", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, IHC-P", "Nox Box", "Frezer 14 (-20)", 0, 4, "", "Discontinued"],
  ["AB96233", "LOXL2", "Abcam", "Rabbit", "P", "", "IgG", "Human", "I-ELISA, IHC-P, WB, ICC/IF", "Nox Box", "Frezer 14 (-20)", 0, 5, "", ""],
  ["AB88186", "LOXL4", "Abcam", "Rabbit", "P", "", "IgG", "Human", "IHC, WB", "Nox Box", "Frezer 14 (-20)", 0, 5, "", "Discontinued"],
  ["AB115841", "OGG1", "Abcam", "Goat", "P", "", "IgG", "Rat, Human", "WB, ELISA, IHC-P", "Nox Box", "Frezer 14 (-20)", 0, 5, "", "Discontinued"],
  ["AB47300", "p-P21", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, IHC-P, ICC/IF", "Nox Box", "Frezer 14 (-20)", 0, 7, "", ""],
  ["AB3611", "RAGE", "Abcam", "Rabbit", "P", "", "IgG", "Mouse", "WB, IHC", "RAGE Box", "Frezer 14 (-20)", 0, 7, "", ""],
  ["AB45977", "Myeloperoxidase", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, IHC, ICC", "RAGE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB215188", "TNF-a", "Abcam", "Rabbit", "M", "EPR20972", "IgG", "Human, Mouse", "WB, Flow, IP, ICC", "RAGE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["10037S", "CD81", "Cell Signaling", "Rabbit", "M", "D5O2Q", "IgG", "Mouse", "WB, IP, IHC, ICC, Flow", "RAGE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["sc113330", "ALIX H293", "Santa Cruz", "Cell Lysate", "", "", "", "Human", "WB", "RAGE Box", "Frezer 14 (-20)", 0, 3, "", ""],
  ["SC2210", "NIH 3T3 Whole Cell", "Santa Cruz", "Cell Lysate", "", "", "", "Mouse", "WB", "RAGE Box", "Frezer 14 (-20)", 0, 2, "", ""],
  ["ab107059", "CLAUDIN 6", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Human", "WB, ICC/IF, IHC-P", "RAGE Box", "Frezer 14 (-20)", 0, 16, "", "Discontinued"],
  ["ab203919", "Nanog", "Abcam", "Rabbit", "M", "EPR19646", "IgG", "Mouse, Human", "IP, WB", "RAGE Box", "Frezer 14 (-20)", 0, 16, "", ""],
  ["ab16731", "Catalase", "Abcam", "Rabbit", "P", "", "IgG", "Human, Mouse, Rat", "IHC, WB, ICC", "RAGE Box", "Frezer 14 (-20)", 0, 14, "", "Discontinued"],
  ["ab34843", "IL-10", "Abcam", "Rabbit", "P", "", "IgG", "Human", "ELISA, WB", "RAGE Box", "Frezer 14 (-20)", 0, 14, "", ""],
  ["ab150075", "Rabbit IgG 647 2nd", "Abcam", "Donkey", "P", "", "", "Rabbit", "Flow Cyt, IHC-P, ICC/IF, ELISA, IHC-Fr", "DNK Box", "Frezer 14 (-20)", 0, 21, "", ""],
  ["ab6802", "Rabbit IgG HRP", "Abcam", "Donkey", "P", "", "IgG", "Rabbit", "ELISA, WB, ICC, IM, Dot, IHC-P, IHC-Fr", "DNK Box", "Frezer 14 (-20)", 0, 18, "", ""],
  ["ab92547", "Vimentin", "Abcam", "Rabbit", "M", "EPR3776", "IgG", "Monkey, Mouse, Rat, Human", "Flow Cyt (Intra), IHC-P, WB, mIHC, ICC/I", "DNK Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab167152", "NRF2 Peptide", "Abcam", "Human", "", "", "", "Peptide", "BL", "DNK Box", "Frezer 14 (-20)", 0, 28, "", "Dicontinued"],
  ["ab80", "CDKN2A/p19ARF", "Abcam", "Rabbit", "P", "", "IgG", "Mouse", "IHC-P, ICC, IHC-Fr, ELISA, WB, ICC/IF", "DNK Box", "Frezer 14 (-20)", 0, 11, "", ""],
  ["AB62352", "NRF2", "Abcam", "Rabbit", "M", "EP1808Y", "IgG", "Human", "WB, ICC/IF, Flow Cyt (Intra)", "DNK Box", "Frezer 14 (-20)", 0, 2, "", ""],
  ["AB98111", "KLOTHO", "Abcam", "Rabbit", "P", "", "IgG", "Human", "IHC-P, WB", "DNK Box", "Frezer 14 (-20)", 0, 4, "", "Discontinued"],
  ["AB5444", "HSP70", "Abcam", "Mouse", "M", "4G4", "IgG1", "Mouse, Human", "IHC-P, ICC/IF, Flow Cyt,WB", "DNK Box", "Frezer 14 (-20)", 0, 6, "", "Discontinued"],
  ["AB108252", "ACE2", "Abcam", "Rabbit", "M", "EPR4435(2)", "IgG", "Human, Mouse, Rat", "I-ELISA, WB, IHC-P, IP", "ACE Box", "Frezer 14 (-20)", 0, 4, "", ""],
  ["AB119695", "Cytokeratin 14", "Abcam", "Rabbit", "M", "SP53", "IgG", "Human, Mouse, Rat", "ICC/IF, WB, mIHC, IHC-P, IHC-Fr, Flow Cyt (Intra)", "ACE Box", "Frezer 14 (-20)", 0, 4, "", ""],
  ["AB75769", "CD146", "Abcam", "Rabbit", "M", "EPR3208", "IgG", "Mouse, Rat, Human", "Flow Cyt (Intra), WB, ICC/IF, IHC-P", "ACE Box", "Frezer 14 (-20)", 0, 8, "", ""],
  ["AB668", "Cytokeratin 18", "Abcam", "Mouse", "M", "C04", "IgG1", "Human", "Flow, IHC", "ACE Box", "Frezer 14 (-20)", 0, 11, "", ""],
  ["NB200117SS", "anti-beta defensin 3", "Novus Biologics", "Rabbit", "P", "", "", "Human, Rat", "ELISA, IHC, WB, ICC", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["NBP176864SS", "CAMP", "Novus Biologics", "Rabbit", "P", "", "", "Human", "WB, IHC, ICC", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab98952", "N-Cadherin", "Abcam", "Mouse", "M", "5D5", "IgG1", "Human, Mouse, Rat", "WB, Flow, IHC, ICC", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["MA1-980", "c-MYC", "Invitrogen", "Mouse", "M", "9E10", "", "Human", "WB, IHC, ICC, IF, IP, ELISA", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2339", "P38 b-MAPK", "Cell Signaling", "Rabbit", "M", "C28C2", "IgG", "Human, Monkey", "WB, IP", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9218", "P38 a-MAPK", "Cell Signaling", "Rabbit", "P", "", "", "Human, Mouse, Rat, Monkey", "WB, IP", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["108831AP", "p16 INK4A", "ProteinTech", "Rabbit", "P", "", "", "Human", "Flow, ICC, IHC, IP", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab92547", "Vimentin", "Abcam", "Rabbit", "M", "EPR3776", "IgG", "Mouse, Rat, Human, Monkey", "Flow Cyt (Intra), IHC-P, WB, mIHC, ICC/IF", "ACE Box", "Frezer 14 (-20)", 1, 2, "", ""],
  ["2697", "p-IKKA/B (Ser 176/180)", "Cell Signaling", "Rabbit", "M", "16A6", "IgG", "Human, Mouse, Rat, Hamster, Monkey", "WB, IHC, Flow", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2677", "Beta-Catenin", "Cell Signaling", "Mouse", "M", "L54E2", "IgG1", "Human", "WB, IP, IF, Flow", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["3762", "ASK1", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human", "WB", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2225", "Caspase 1", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human", "WB", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["8089", "ATG16L1", "Cell Signaling", "Rabbit", "M", "D6D5", "IgG", "Human, Mouse, Rat", "WB, IP, IF", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["8662", "ASK1", "Cell Signaling", "Rabbit", "M", "D11C9", "IgG", "Human, Mouse, Rat, Monkey", "WB, IP", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["3935", "HMGB1", "Cell Signaling", "Rabbit", "P", "", "", "Human, Mouse, Rat, Monkey", "WB, IF", "ACE Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["3548", "p-GSK3b (Thr390)", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human", "WB", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2750", "OCT_4", "Cell Signaling", "Rabbit", "P", "", "", "Human", "WB, IHC, IF, Flow, Chromatin IP", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab13243", "Heme Oxygenase 1", "Abcam", "Rabbit", "P", "", "IgG", "Human, Mouse, Rat", "WB, IHC, ICC, ELISA", "ACE Box", "Frezer 14 (-20)", 0, 8, "", ""],
  ["AB22551", "y-H2AX", "Abcam", "Mouse", "M", "3F2", "IgG1", "Human, Mouse", "WB, Flow, IHC, ICC", "ACE Box", "Frezer 14 (-20)", 0, 3, "", ""],
  ["AB81292", "p-ATM (S1981)", "Abcam", "Rabbit", "M", "EP1890Y", "IgG", "Human", "WB, Flow, IP, IHC, Dot Blot", "ACE Box", "Frezer 14 (-20)", 0, 5, "", ""],
  ["AB4182", "TRF2", "Abcam", "Rabbit", "P", "", "IgG", "Human", "ICC, WB", "ACE Box", "Frezer 14 (-20)", 0, 11, "", "Discontinued"],
  ["SAB4504720", "p-p16 INK4A (Ser152)", "Sigma", "Rabbit", "P", "", "IgG", "Human, Rat, Mouse", "ELISA, IHC, WB", "ACE Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["A5441", "b-actin", "Millipore", "Mouse", "M", "AC-15", "IgG", "Rat", "WB", "ACE Box", "Frezer 14 (-20)", 1, 0, "", "Discontinued"],
  ["3033", "p-NFKB P65 (S536)", "Cell Signaling", "Rabbit", "M", "93H1", "IgG", "Human, Mouse, Rat, Hamster, Monkey, Pig", "WB, IP, IF, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["4764", "NFKB P65", "Cell Signaling", "Rabbit", "M", "C22B4", "IgG", "Human, Mouse, Rat, Monkey, Cow", "WB, IF, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab194926", "p-NFKB P65 (s311)", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, IHC, ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab76302", "p-NFKB P65 (S536)", "Abcam", "Rabbit", "M", "EPR2294Y", "IgG", "Human, Mouse, Rat", "WB, IP, Dot Blot", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["ab97726", "p-NFKB P65 (S529)", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, IHC, ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab32536", "NFKB P65", "Abcam", "Rabbit", "M", "E379", "IgG", "Mouse, Human", "WB, IP, IHC-P, ICC/IF", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["9139", "STAT3", "Cell Signaling", "Mouse", "M", "124H6", "IgG2a", "Human, Mouse, Rat, Monkey", "WB, IP, IHC, IP, Flow, Chromatin IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9145", "p-STAT3 (Y705)", "Cell Signaling", "Rabbit", "M", "D3A7", "IgG", "Human, Mouse, Rat, Monkey", "WB, IP, IHC, ICC, Flow, Chromatin IP, IP-seq", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab267373", "p-STAT3 (Y705)", "Abcam", "Rabbit", "M", "EPR23968", "IgG", "Human", "WB, Flow, IP, IHC, ICC, ChIP, Dot Blot", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab76315", "p-STAT3 (Y705)", "Abcam", "Rabbit", "M", "EPR2147Y", "IgG", "Human, Mouse", "WB, Flow, IP, IHC, ICC, ELISA, Dot Blot", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab31370", "STAT3", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Rat, Human", "ELISA, WB, IHC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2697", "p-IKK alpha/beta (Ser176/180)", "Cell Signaling", "Rabbit", "M", "16A6", "IgG", "Human, Mouse, Rat, Monkey, Hamster", "WB, IHC, Flow", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["2859", "p-IKB alpha (S32)", "Cell Signaling", "Rabbit", "M", "14D4", "IgG", "Human, Mouse, Rat, Monkey", "WB, IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab133462", "p-IKB alpha (S36)", "Abcam", "Rabbit", "M", "EPR6235", "IgG", "Human, Mouse, Rat", "WB, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab194528", "p-IKK B (S176/S177)", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Human, Rat", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9252", "SAPK/JNK", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human, Mouse, Rat, Hamser, Monkey, Zebrafish, Cow, S. cervisiea", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["3678", "Anti-RB 2nd", "Cell Signaling", "Mouse", "M", "L27A9", "IgG", "Mouse", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab32518", "IKB Alpha", "Abcam", "Rabbit", "M", "E130", "IgG", "Human, Mouse, Rat", "WB, Flow, IP, IHC, ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab109457", "STAT1", "Abcam", "Rabbit", "M", "EPR3147", "IgG", "Human", "WB, Dot Blot", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab28146", "Cytochrome P450 2E1", "Abcam", "Rabbit", "P", "", "IgG", "Human, Mouse, Rat, Rabbit", "WB", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["ab219413", "MYD88", "Abcam", "Rabbit", "M", "EPR21824", "IgG", "Human, Mouse, Rat", "WB, IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab25377", "Ly6g + Ly6c", "Abcam", "Rabbit", "M", "RB6-8C5", "IgG", "Mouse", "IHC-P, Flow Cyt, IHC-Fr", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["4695", "p44/42 MAPK (Erk1/2)", "Cell Signaling", "Rabbit", "M", "137F5", "IgG", "Human, Mouse, Rat, Hamster, Monkey, Mink, Fly, Zebrafish, Cow, Dog, Pig, C.elegans", "WB, IP, IHC, IF, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9251", "p-SAPK/JNK (Thr183/Tyr185)", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human, Mouse, Rat, Hamster, Donkey, Cow, Sheep", "WB, IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab62584", "SOC1", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", "Discontinued"],
  ["2779", "SOC2", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human, Rat, Mouse", "WB, IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab3692", "SOC2", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Rat, Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", "Discontinued"],
  ["ab245246", "SLCO2B1/OATP2B1", "Abcam", "Rabbit", "M", "EPR22212", "IgG", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab214819", "MCP1", "Abcam", "Rabbit", "M", "EPR21025", "IgG", "Human", "WB, ICC, IP, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab39184", "TIMP3", "Abcam", "Rabbit", "P", "", "IgG", "Human, Mouse", "WB, ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["MAB4155", "Human Integrin beta 6", "Millipore", "Mouse", "M", "437211", "IgG2A", "Human", "Flow, ICC, CY-TOF", "Inflammation Box", "Frezer 14 (-20)", 1, 1, "", ""],
  ["ab229193", "BCRP/ABCG2", "Abcam", "Rabbit", "M", "", "IgG", "Human", "Flow, ICC, IHC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab207732", "BCRP/ABCG2", "Abcam", "Rabbit", "M", "EPR20080", "IgG", "Human, Mouse, Rat", "WB, Flow, IHC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab170904", "P Glycoprotein", "Abcam", "Rabbit", "M", "EPR10364-57", "IgG", "Human, Rat, Mouse", "WB, IHC", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["ab3452", "EBP50/NHERF-1", "Abcam", "Rabbit", "P", "", "IgG", "Human, Mouse, Rat, Dog", "ICC, WB, IP, IHC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2972", "mTOR", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human, Mouse, Rat, Monkey", "WB, IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["13987", "c-Myc/N-Myc", "Cell Signaling", "Rabbit", "M", "D3N8F", "IgG", "Human, Mouse, Rat, Monkey", "WB, IF, Flow, Chromatin IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab34710", "Collagen I + Collagen III antibody", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, ICC/IF, IHC-P", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["14630", "p-GSK3 B (Ser9)", "Cell Signaling", "Mouse", "M", "D2Y9Y", "IgG1", "Human, Mouse, Rat", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["3548", "p-GSK3 B(Thr390)", "Cell Signaling", "Rabbit", "P", "", "", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9323", "p-GSK3 B (Ser9)", "Cell Signaling", "Rabbit", "M", "5B3", "IgG", "Human, Mouse, Rat, Monkey", "WB, IHC, ICC", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["12456", "GSK3 b", "Cell Signaling", "Rabbit", "M", "D5C5Z", "IgG", "Human, Mouse, Rat, Monkey", "WB, IP, IHC, ICC, Flow", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["3762", "ASK1", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["4915", "CD45/ICAM1", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["13174", "CD9", "Cell Signaling", "Rabbit", "M", "D8O1A", "IgG", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab2215", "CD9", "Abcam", "Mouse", "M", "MEM-61", "IgG1", "Human", "Mass Cytometry, IHC-P, Flow Cyt", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2750", "OCT_4", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human", "WB, IHC, IF, Flow, Chromatin IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab181557", "OCT_4", "Abcam", "Rabbit", "M", "EPR17929", "IgG", "Mouse, Human", "ICC/IF, ChIP-seq, ChIP, IHC-P, IP, Flow Cyt (Intra), WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9561", "p-b Catenin (Ser33/37/Thr41)", "Cell Signaling", "Rabbit", "P", "", "", "Human, Mouse, Rat, Monkey", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["8480", "b-Catenin", "Cell Signaling", "Rabbit", "M", "D10A8", "IgG", "Human, Mouse, Rat, Monkey", "WB, IP, IHC, ICC, Flow, Chromatin IP, IP-seq", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["8814", "Active b-Catenin (Ser33/37/Thr41)", "Cell Signaling", "Rabbit", "M", "D13A1", "IgG", "Human, Mouse, Rat, Monkey", "WB, IP, IHC, ICC, Flow, Chromatin IP, IP-seq", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["12280", "p-MMK3 MKK3 (Ser189)/MKK6 (Ser207)", "Cell Signaling", "Rabbit", "M", "D8E9", "IgG", "Human, Mouse, Rat, Monkey", "WB, IP, ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["13667", "MMP-9", "Cell Signaling", "Rabbit", "M", "D3O3H", "IgG", "Human", "WB, IHC, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["79769", "HLA-G", "Cell Signaling", "Rabbit", "M", "E8N9C", "IgG", "Human", "WB, IHC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9368", "PKC Zeta", "Cell Signaling", "Rabbit", "M", "C24E6", "IgG", "Human, Mouse, Rat, Monkey", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["3178", "Progestrone Receptor B", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", "Discontinued"],
  ["NBP267338", "p-RB1 (Ser807)", "Novus Biologics", "Rabbit", "M", "", "IgG", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", "Discontinued"],
  ["F3648", "Fibronectin", "Sigma", "Rabbit", "P", "", "IgG", "Human", "ELISA, IF, WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["MA5-15073", "p-TAK1 (Thr184, Thr187)", "Invitrogen", "Rabbit", "M", "", "IgG", "Human, Mouse, Rat", "WB, IHC, ICC, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["MAB91472", "IFN-epsilon", "R&D Systems", "Mouse", "M", "995728", "IgG1", "Human", "ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["NBP224821", "TLR4", "Novus Biologics", "Rabbit", "P", "", "IgG", "Human, Mouse, Pig", "WB, Flow, ICC/IF, IHC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB202417", "iNOS+nNOS antibody", "Abcam", "Rabbit", "M", "[EP16634]", "IgG", "Mouse, Human", "ELISA, WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9219", "p-P38 MAPK (Thr180/Tyr182) Sepharose Beads", "Cell Signaling", "Mouse", "", "", "", "Human, Mouse, Rat, Monkey, Sheep", "IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["4893", "Nanog", "Cell Signaling", "Mouse", "M", "1E6C4", "IgG1", "Human", "WB, IHC, IF, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["3580", "Nanog", "Cell Signaling", "Rabbit", "P", "", "IgG", "Human", "WB, IF, Flow, Chromatin IP", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB5989", "PHAP", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Rat, Human", "ICC, WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", "Discontinued"],
  ["AB64613", "Glutamine Synthetase", "Abcam", "Mouse", "M", "3B6", "IgG1", "Drosophila melanogaster, Human, Mouse, Rat, Zebrafish", "WB, Flow, IHC, ICC, ELISA", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB7260", "GFAP", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Rat", "WB, IP, IHC, ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB187091", "p-MLKL (S358)", "Abcam", "Rabbit", "M", "EPR9514", "IgG", "Human", "WB, IHC, Dot Blot", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB124917", "Liver Arginase", "Abcam", "Rabbit", "M", "EPR6671B", "IgG", "Human, Mouse", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB184718", "MLKL", "Abcam", "Rabbit", "M", "EPR1714", "IgG", "Human", "WB, IHC, ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["AB86935", "VEGF 121 Protein", "Abcam", "", "", "", "", "Human", "WB", "Inflammation Box", "Frezer 14 (-20)", 8, 0, "", "Discontinued"],
  ["2435", "PPAR gamma", "Cell Signaling", "Rabbit", "M", "(C26H12)", "IgG", "Human, Mouse", "WB, IHC, IF, Chromatin IP", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["SC-2210", "NIH/3T3 Whole Cell Lysate", "Santa Cruz", "Mouse", "", "", "", "", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["bs-1278r", "8-OHdG/8 Hydroxyguanosine", "BioUSA", "Rabbit", "P", "", "IgG", "", "IHC, ICC, ELISA", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["MAB8929", "b-actin", "R&D Systems", "Mouse", "M", "937215", "IgG1", "Human, Mouse, Rat,", "WB, ICC, IHC, IP, FA", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["7076P2", "Anti-mouse IgG, HRP-linked Antibody", "Cell Signaling", "Horse", "P", "", "", "Mouse", "WB", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["9212", "p38 MAPK", "Cell Signaling", "Rabbit", "P", "", "", "Human, Mouse, Rat, Monkey, Guinea Pig", "WB, IHC, Flow", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["4511", "p-P38 MAPK (Thr180/Tyr182)", "Cell Signaling", "Rabbit", "M", "D3F9", "IgG", "Human, Mouse, Rat, Monkey, Mink, Pig, Sheep", "WB, IP, IHC, IP, Flow", "Inflammation Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["AB8227", "b-actin", "Abcam", "Rabbit", "P", "", "", "Chicken, Chinese hamster, Cow, Dog, Fish, Human, Mouse, Rabbit, Rat, Xenopus laevis", "Western Blot, IHC-P, ICC/IF", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["MBS31352", "Ureaplasma Parvum", "MyBioSource", "Mouse", "M", "", "IgG1", "Ureaplasma Parvum", "ELISA, IF", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab150157", "Goat anti-Rat IgG 2nd", "Abcam", "Goat", "", "", "IgG", "Rat", "Flow, ICC", "Inflammation Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2956", "GFP", "Cell Signaling", "Rabbit", "M", "D5.1", "IgG", "All", "WB, IHC", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab178847", "Iba1", "Abcam", "Rabbit", "M", "EPR16589", "IgG", "Mouse, Rat, Human", "IHC (PFA fixed), IHC-P, WB, IP, ICC/IF, IHC-Fr", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab9100", "TLR2", "Abcam", "Mouse", "M", "TL2.1", "IgG2a", "Human, Common marmoset", "ICC/IF, WB, IP, FuncS (Neut/Block), Flow Cyt, FuncS", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["18634", "Flotillin-1", "Cell Signaling", "Rabbit", "M", "D2V7J", "IgG", "Human, Mouse, Rabbit", "WB, IP, IHC, IF", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["EXOAB-CD9A", "CD9", "SBI", "Rabbit", "P", "", "IgG", "Human", "WB", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["EXOAB-CD81A", "CD81", "SBI", "Rabbit", "P", "", "IgG", "Human", "WB", "Exosome Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["EXOAB-CD63A", "CD63", "SBI", "Rabbit", "P", "", "IgG", "Human", "WB", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["EXOAB-HSP70A-1", "HSP70", "SBI", "Rabbit", "P", "", "IgG", "Human", "WB", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["", "2nd Goat Rabbit HRP", "SBI", "Goat", "P", "", "IgG", "Human", "WB", "Exosome Box", "Frezer 14 (-20)", 2, 0, "", ""],
  ["ab133267", "Syntenin", "Abcam", "Rabbit", "M", "EPR8102", "IgG", "Human", "WB, Flow, IP, IHC, ICC", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2433", "Calnexin", "Cell Signaling", "Rabbit", "P", "", "", "Human", "WB, IHC, IF", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["12480", "GM130", "Cell Signaling", "Rabbit", "M", "D6B1", "IgG", "Human, Monkey", "WB, IP, IF", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["52090", "CD63", "Cell Signaling", "Rabbit", "M", "E1W3T", "IgG", "Human, Monkey", "WB", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["2171", "Alix", "Cell Signaling", "Mouse", "M", "3A9", "IgG1", "Human, Mouse, Rat, Monkey", "WB, IP", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["13174", "CD9", "Cell Signaling", "Rabbit", "M", "D8O1A", "IgG", "Human", "WB", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["3350", "ApoA1", "Cell Signaling", "Mouse", "M", "5F4", "IgG1", "Human", "WB", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["4929", "Albumin", "Cell Signaling", "Rabbit", "P", "", "", "Human, Mouse, Rat", "WB", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["NBP286666", "HERV", "Novus Biologics", "Rabbit", "P", "", "IgG", "Human", "WB", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["67965", "MFSD2", "ProteinTech", "Mouse", "M", "", "IgG2a", "Human, Mouse", "WB, ELISA", "Exosome Box", "Frezer 14 (-20)", 1, 0, "", ""],
  ["ab233923", "CD146", "Abcam", "Mouse", "M", "1130", "IgG1", "Human", "IHC", "Exosome Box", "Frezer 14 (-20)", 1, 2, "", ""],
  ["ab75769", "CD146", "Abcam", "Rabbit", "M", "EPR3208", "IgG", "Human, Mouse, Rat", "WB, Flow, IHC, ICC", "Exosome Box", "Frezer 14 (-20)", 1, 6, "", ""],
  ["ab221003", "Alexa 568 Iba1", "Abcam", "Rabbit", "M", "EPR6136(2)", "IgG", "Human", "ICC, Flow, IHC", "Exosome Box", "Frezer 14 (-20)", 1, 9, "", ""],
  ["ab2213", "ICAM1", "Abcam", "Mouse", "M", "MEM-11", "IgG2a", "Human", "WB, Flow", "Antibody Box 5", "Frezer 14 (-20)", 1, 5, "", ""],
  ["ab98952", "N-Cadherin", "Abcam", "Mouse", "M", "5D5", "IgG1", "Human, Mouse, Rat", "WB, Flow, IHC, ICC", "Antibody Box 5", "Frezer 14 (-20)", 1, 1, "", ""],
  ["ab236630", "CD9", "Abcam", "Rabbit", "M", "EPR23105", "IgG", "Human", "WB, Flow, IP, IHC, ICC", "Antibody Box 5", "Frezer 14 (-20)", 1, 9, "", ""],
  ["ab92547", "Vimentin", "Abcam", "Rabbit", "M", "EPR3776", "IgG", "Mouse, Rat, Human, Monkey", "Flow Cyt (Intra), IHC-P, WB, mIHC, ICC/IF", "Antibody Box 5", "Frezer 14 (-20)", 1, 2, "", ""],
  ["AB5103", "Histone H3", "Abcam", "Rabbit", "P", "", "IgG", "Mouse, Rat, Human", "PepArr, IP, WB", "Antibody Box 5", "Frezer 14 (-20)", 1, 3, "", ""],
  ["AB50247", "PAD14", "Abcam", "Rabbit", "P", "", "IgG", "Human", "ICC/IF, ELISA, WB, IP", "Antibody Box 5", "Frezer 14 (-20)", 1, 8, "", ""],
  ["AB64425", "PSG9", "Abcam", "Rabbit", "P", "", "IgG", "Human", "ICC, WB", "Antibody Box 5", "Frezer 14 (-20)", 1, 9, "", "Discontinued"],
  ["ab68707", "Galectin 13", "Abcam", "Mouse", "P", "", "IgG", "Human", "WB", "Antibody Box 5", "Frezer 14 (-20)", 1, 4, "", "Discontinued"],
  ["AF3578", "TAB1", "R&D Systems", "Goat", "P", "", "IgG", "Human, Mouse", "WB, ICC, IHC, ICC", "Antibody Box 5", "Frezer 14 (-20)", 1, 19, "", ""],
  ["AB52237", "COX2", "Abcam", "Rabbit", "P", "", "IgG", "Human", "WB, ICC", "Antibody Box 3", "Frezer 14 (-20)", 0, 5, "", ""],
  ["AB45178", "ASK1", "Abcam", "Rabbit", "M", "EP553Y", "IgG", "Human, Mouse", "IHC, WB, ICC, Flow", "Antibody Box 3", "Frezer 14 (-20)", 0, 2, "", ""],
  ["PA534753", "IL-22", "Invitrogen", "Rabbit", "P", "", "IgG", "Human", "WB, IHC, ELISA", "Antibody Box 3", "Frezer 14 (-20)", 1, 6, "", ""],
  ["ab197593", "Ketohexokinase", "Abcam", "Rabbit", "M", "EPR15847", "IgG", "Mouse, Rat, Human", "IHC, ICC, WB, IP", "Antibody Box 3", "Frezer 14 (-20)", 1, 1, "", ""],
  ["MA1980", "c-MYC Epitotope Tagged", "Invitrogen", "Mouse", "M", "9E10", "IgG1", "Human", "WB, IHC, ICC, Flow, ELISA, IP, ChIP", "Antibody Box 3", "Frezer 14 (-20)", 1, 7, "", ""],
  ["MA515597", "GSK3 b", "Invitrogen", "Mouse", "M", "3D10", "IgG2a", "Human, Mouse, Monkey, Rat", "WB, IHC, ICC, Flow, ELISA", "Antibody Box 3", "Frezer 14 (-20)", 1, 5, "", ""],
  ["AB115841", "OGG1", "Abcam", "Goat", "P", "", "IgG", "Rat, Human", "WB, ELISA, IHC-P", "Antibody Box 3", "Frezer 14 (-20)", 1, 4, "", "Discontinued"],
  ["ab4637", "BUBR1", "Abcam", "Mouse", "M", "8G1", "IgG1", "Human", "IP, ICC, WB", "Antibody Box 3", "Frezer 14 (-20)", 1, 14, "", "Discontinued"],
  ["ab34771", "RFP - Biotin", "Abcam", "Rabbit", "P", "", "IgG", "RFP Proteins", "WB", "Antibody Box 3", "Frezer 14 (-20)", 1, 14, "", ""],
  ["ab6658", "GFP-Biotin", "Abcam", "Goat", "P", "", "IgG", "GFP Proteins", "WB, IHC, IP, ICC, ELISA", "Antibody Box 3", "Frezer 14 (-20)", 1, 9, "", ""],
  ["NBP219302", "RFP", "Novus Biologics", "Rabbit", "P", "", "IgG", "ALL - RFP protiens", "WB, ICC, IP", "Antibody Box 3", "Frezer 14 (-20)", 1, 14, "", ""],
  ["610296", "eNOS/NOS Type 3", "BD Biosciences", "Mouse", "P", "", "IgG1", "Human", "WB, IP, ICC, IHC", "Antibody Box 2", "Frezer 14 (-20)", 1, 1, "", ""],
  ["ab32152", "VEGF Receptor 1", "Abcam", "Rabbit", "M", "Y103", "IgG", "Mouse, Human, Hamster, Rat", "WB, IP, IHC", "Antibody Box 3", "Frezer 14 (-20)", 1, 4, "", ""],
  ["ab175430", "Twist", "Abcam", "Mouse", "M", "10E4E6", "IgG1", "Human, Mouse", "WB, Flow, IHC, ICC", "Antibody Box 4", "Frezer 14 (-20)", 0, 1, "", ""],
  ["ab16965", "Thioredoxin / TRX", "Abcam", "Mouse", "M", "3A1", "IgG2b", "Human", "WB, ELISA, Flow, IP", "Antibody Box 5", "Frezer 14 (-20)", 0, 8, "", "Discontinued"],
  ["ab43151", "SP100", "Abcam", "Rabbit", "P", "", "IgG", "Human", "IHC, WB, ChIP", "Antibody Box 6", "Frezer 14 (-20)", 1, 6, "", "Discontinued"],
  ["ab8219", "CD63", "Abcam", "Mouse", "M", "MEM-259", "IgG1", "Human", "Flow, IHC", "Antibody Box 7", "Frezer 14 (-20)", 1, 5, "2016", ""],
  ["ab2215", "CD9", "Abcam", "Mouse", "M", "MEM-61", "IgG1", "Human", "Flow, Mass, IHC", "Antibody Box 8", "Frezer 14 (-20)", 1, 9, "2018", ""],
  ["ab654", "GLUT4", "Abcam", "Rabbit", "P", "", "IgG", "Human", "ICC, IHC", "Antibody Box 9", "Frezer 14 (-20)", 1, 19, "", ""],
  ["12163", "IL-10", "Cell Signaling", "Rabbit", "M", "D13A11", "IgG", "Human", "WB", "", "Brinley  -20C", 2, 0, "", "Use only BSA"],
  ["34265", "Folate Receptor Alpha", "Cell Signaling", "Mouse", "M", "E8U2F", "IgG1 Kappa", "Human, Mouse", "WB, IHC", "", "Brinley  -20C", 1, 0, "", ""],
  ["60269", "IL-10", "ProteinTec", "Mouse", "M", "8E4B6", "IgG2b", "Human, Rat, Monkey, Pig, Zebrafish", "WB, IHC, IF/ICC, ELISA", "", "Brinley  -20C", 1, 0, "", ""]
];
